-- 2026 OT Beyond Borders — 접수 테이블 (Supabase 정본)
-- Supabase Dashboard > SQL Editor 에서 실행

-- ── 공통: 동기화 상태 ──
-- status: pending → complete → synced | sync_failed

create table if not exists submissions_ceu_clinician (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text not null,
  courses text,
  ceu_apply text,
  kaot_id text,
  kaot_grade text,
  license_no text,
  career_years text,
  fee_total text,
  pay_method text,
  payer_name text,
  refund_bank text,
  refund_account text,
  certificate text,
  agree_payment text,
  agree_refund text,
  agree_privacy text,
  status text not null default 'pending',
  synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now()
);

create table if not exists submissions_ceu_student (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  birth text,
  affiliation text,
  phone text not null,
  email text not null,
  courses text,
  fee_total text,
  pay_method text,
  payer_name text,
  refund_bank text,
  refund_account text,
  certificate text,
  agree_payment text,
  agree_refund text,
  agree_privacy text,
  status text not null default 'pending',
  synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now()
);

create table if not exists submissions_workshop (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  affiliation text not null,
  degree text,
  degree_etc text,
  email text not null,
  phone text not null,
  interest text,
  payer_name text,
  agree_payment text,
  refund_bank text,
  refund_account text,
  agree_refund text,
  agree_privacy text,
  status text not null default 'pending',
  synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now()
);

create table if not exists submissions_poster (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  affiliation text not null,
  phone text not null,
  email text not null,
  author_role text,
  pres_type text,
  poster_count text,
  title text not null,
  co_authors text,
  field text,
  abstract_format text,
  fee_confirm text,
  agree_privacy text,
  abstract_file_path text,
  abstract_file_url text,
  status text not null default 'pending',
  synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now()
);

create table if not exists submissions_oral (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  birth text,
  phone text not null,
  grad_school text,
  degree_date text,
  journal_status text,
  journal_detail text,
  title text not null,
  thesis_language text,
  degree_type text,
  advisor text,
  committee text,
  field text,
  summary_research text,
  summary_contribution text,
  summary_importance text,
  agree_privacy text,
  recommendation_file_path text,
  recommendation_file_url text,
  grad_cert_file_path text,
  grad_cert_file_url text,
  similarity_file_path text,
  similarity_file_url text,
  thesis_file_path text,
  thesis_file_url text,
  status text not null default 'pending',
  synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now()
);

create table if not exists submissions_capstone (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  affiliation text not null,
  grade text,
  phone text not null,
  email text not null,
  team_name text,
  team_size text,
  team_members text,
  title text not null,
  advisor_name text,
  advisor_phone text,
  advisor_email text,
  agree_competition text,
  agree_privacy text,
  capstone_file_path text,
  capstone_file_url text,
  status text not null default 'pending',
  synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now()
);
